<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPUAODEW00BA" failures="4" tests="8" name="com.epam.calculator.tests.MultWithDoubleTest" time="0.003" errors="0" timestamp="2022-09-26T12:36:28 EEST" skipped="0">
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.000"/>
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.001">
    <failure message="Multiplicand was -77823.33, multiplier was -5657.44; did not expect to find [4.4028082007519996E8] but found [4.4028082E8]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Multiplicand was -77823.33, multiplier was -5657.44; did not expect to find [4.4028082007519996E8] but found [4.4028082E8]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at com.epam.calculator.tests.MultWithDoubleTest.multWithDoubleTest(MultWithDoubleTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- multWithDoubleTest -->
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.000"/>
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.000">
    <failure message="Multiplicand was -77823.33, multiplier was 5657.44; did not expect to find [-4.4028082007519996E8] but found [-4.40280821E8]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Multiplicand was -77823.33, multiplier was 5657.44; did not expect to find [-4.4028082007519996E8] but found [-4.40280821E8]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at com.epam.calculator.tests.MultWithDoubleTest.multWithDoubleTest(MultWithDoubleTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- multWithDoubleTest -->
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.001"/>
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.000">
    <failure message="Multiplicand was 19234.7457, multiplier was 763.99; did not expect to find [1.4695153367343E7] but found [1.4695153E7]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Multiplicand was 19234.7457, multiplier was 763.99; did not expect to find [1.4695153367343E7] but found [1.4695153E7]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at com.epam.calculator.tests.MultWithDoubleTest.multWithDoubleTest(MultWithDoubleTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- multWithDoubleTest -->
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.000"/>
  <testcase classname="com.epam.calculator.tests.MultWithDoubleTest" name="multWithDoubleTest" time="0.001">
    <failure message="Multiplicand was 19234.7457, multiplier was -763.99; did not expect to find [-1.4695153367343E7] but found [-1.4695154E7]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Multiplicand was 19234.7457, multiplier was -763.99; did not expect to find [-1.4695153367343E7] but found [-1.4695154E7]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at com.epam.calculator.tests.MultWithDoubleTest.multWithDoubleTest(MultWithDoubleTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- multWithDoubleTest -->
</testsuite> <!-- com.epam.calculator.tests.MultWithDoubleTest -->
